name: deployApp
description: Deploy a container image to a Kubernetes deployment
inputs:
  environment:
    description: Target environment (e.g., dev, prod)
    required: true
  namespace:
    description: Kubernetes namespace
    required: true
  deployment:
    description: Kubernetes deployment name
    required: true
  container:
    description: Container name in the deployment
    required: true
  image:
    description: Container image URI
    required: false
    default: ''
  kubeconfigCredentialId:
    description: GitHub secret name for kubeconfig file
    required: false
    default: ''
  rolloutTimeout:
    description: Rollout status timeout (e.g., 180s)
    required: false
    default: 180s
runs:
  using: composite
  steps:
  - name: Validate required inputs
    run: "missing=\"\"\nfor key in environment namespace deployment container; do\n\
      \  value=\"${{ inputs[$key] }}\"\n  if [ -z \"$value\" ]; then\n    echo \"\
      deployApp: missing required input '$key'\"\n    missing=1\n  fi\ndone\nif [\
      \ -z \"${{ inputs.image }}\" ] && [ -z \"${IMAGE_URI:-}\" ]; then\n  echo \"\
      deployApp: image is required (pass input 'image' or set env.IMAGE_URI)\"\n \
      \ exit 1\nfi\nif [ ! -z \"$missing\" ]; then\n  exit 1\nfi\n"
    shell: bash
  - name: Set image variable
    run: "if [ -n \"${{ inputs.image }}\" ]; then\n  echo \"IMAGE_TO_DEPLOY=${{ inputs.image\
      \ }}\" >> $GITHUB_ENV\nelif [ -n \"${IMAGE_URI:-}\" ]; then\n  echo \"IMAGE_TO_DEPLOY=${IMAGE_URI}\"\
      \ >> $GITHUB_ENV\nfi\n"
    shell: bash
  - name: Show deployment info
    run: echo "Deploying ${{ inputs.deployment }} to ${{ inputs.environment }}/${{
      inputs.namespace }} with image ${IMAGE_TO_DEPLOY}"
    shell: bash
  - name: Write kubeconfig to file
    run: "KUBECONFIG_SECRET=\"${{ inputs.kubeconfigCredentialId }}\"\nif [ -z \"$KUBECONFIG_SECRET\"\
      \ ]; then\n  KUBECONFIG_SECRET=\"kubeconfig-${{ inputs.environment }}\"\nfi\n\
      KUBECONFIG_PATH=\"$RUNNER_TEMP/kubeconfig\"\necho \"${!KUBECONFIG_SECRET}\"\
      \ > \"$KUBECONFIG_PATH\"\necho \"KUBECONFIG_PATH=$KUBECONFIG_PATH\" >> $GITHUB_ENV\n"
    shell: bash
    env:
      kubeconfig-${{ inputs.environment }}: ${{ secrets[format('kubeconfig-{0}', inputs.environment)]
        }}
      KUBECONFIG_FILE: ${{ secrets[inputs.kubeconfigCredentialId] }}
  - name: Set image and rollout deployment
    run: 'set -euo pipefail

      export KUBECONFIG="${KUBECONFIG_PATH}"

      kubectl -n "${{ inputs.namespace }}" set image deployment/"${{ inputs.deployment
      }}" "${{ inputs.container }}"="${IMAGE_TO_DEPLOY}"

      kubectl -n "${{ inputs.namespace }}" rollout status deployment/"${{ inputs.deployment
      }}" --timeout="${{ inputs.rolloutTimeout }}"

      '
    shell: bash
